[project]
name = "fastapi-concurrency"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black>=25.1.0",
    "fastapi>=0.115.12",
    "locust>=2.34.0",
    "uvicorn>=0.34.0",
]

